apiVersion: v1
kind: Service
metadata:
  name: "{{ include "be-helm.fullname" . }}-{{ .Values.beservice.name }}"
  labels:
    app.kubernetes.io/name: {{ include "be-helm.name" . }}
    helm.sh/chart: {{ include "be-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.beservice.type }}
  ports:
    - port: {{ .Values.beservice.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "be-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
